name: Build and Deploy
on: push
env:
  CNAME: "school-card.mahdi.pro"
jobs:
  build_and_deploy_frontend:
    name: Build and deploy
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: frontend
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn
      - name: Build site
        run: yarn run build
      - name: Add CNAME
        run: echo $CNAME > dist/CNAME
      - name: Configure Git
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git
      - name: Deploy site to Github Pages
        run: npx gh-pages -d dist
